### ISSUE TITLE
Kubernetes native entities names 

### ISSUE THREAD

**Issue by mancubus77** [open-cluster-management/application-ui#1069]
ACM 2.2 on OCP doesn't follow OpenShift entities names and display "Deployemntconfig" instead of "DeploymentConfig" Also d3 has a weird carriage return in node title after 12 character:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/16170560/113296149-d6754180-9344-11eb-8ffd-745045505686.png">

Proposed title on topology:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/16170560/113296235-ee4cc580-9344-11eb-8f72-7d030f31f37a.png">

**Comment by birsanv** [comment]
@richiepiya can you please review the proposed changes with the UX team to make sure they agree this update

**Comment by richiepiya** [comment]
From my discussion with @jackiwakin and @imjoyjean, the camelCasing is good since OCP has it that way as well. 
As for the wrapping text, we would still need a maximum character limit since one of the longer resource type labels could overlap itself.

<img width="535" alt="Screen Shot 2021-04-06 at 11 37 39 AM" src="https://user-images.githubusercontent.com/39634227/113745545-5d267780-96d3-11eb-8d8d-691a95b6d1f1.png">

One recommendation could be to limit each line to about 20 or 22 characters but also wrap the label based on the camel casing. Ex: "SecurityContextConstraints" (26 letters) is too long so we could split it into 2 lines: "SecurityContext" and "Constraints". In this case, we wouldn't want to split it based on character count because then it would be "SecurityContextConstra" and "ints".

**Comment by birsanv** [comment]
thank you @richiepiya for the quick response, this is great feedback
Based on the screen cap above I understand we still need to have the names separated by spaces, as it is at the moment
( so use **Security Context Constraints** and not **SecurityContextConstraints** , etc )
@mancubus77 let me know if there are any concerns with this, if not can you please update your PR accordingly; we can integrate the camel case but not the second change

**Comment by mancubus77** [comment]
Thank you for the comment. I think we still can use multiLines with entities longer than 18 characters.
```<javascript>
let input = "MySuperSecureGroupWithPolicy";
// let input = "MySuper";
let regex = /[A-Z][a-z']+(?: [A-Z][a-z]+)*/g;
let result = input.match(regex);
let limit = 10
if (input.length > limit) {
    let newString = "";
    for ( var idx = 0; newString.length < limit; idx++ ){
        newString += result[idx];
    }
    result.splice(idx, 0, "\n");
    console.log(result.join(""));
} else {
    console.log(input)
}
```
https://jsfiddle.net/bqo64frt/

**Comment by mancubus77** [comment]
I've pushed new version and added JTest suggested by @birsanv

**Comment by birsanv** [comment]
thank you @mancubus77 the tests are still failing, probably the test fixes I suggested are outdated by your new updates

You can try to run the tests before pushing your fixes, it's easier then to test directly on the PR
```npm run test:update-snapshot```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/open-cluster-management_application-ui/1068/pull-ci-open-cluster-management-application-ui-main-unit-tests/1379425536220073984/artifacts/test/build-log.txt

I'll let @richiepiya to review and comment on your suggested change
I am wondering though how using multilines only for strings with chars longer then 18 would work on different zoom sizes
Could you also attach some screen caps showing the new UI based on your latest changes

And one last comment .. I noticed the platform.properties files you are pushing has a styling update which reports quite a lot of changes you actually did not actively do. It is hard to find your real changes, if at all possible can you try to push only those
https://github.com/open-cluster-management/application-ui/pull/1068/files#diff-7c210d72a8b8b820866c4c92343108a10a25a185ed64c95c1878adff78c7e0e3L13

**Comment by mancubus77** [comment]
Thank you @birsanv 
1. `platform.properties` reverted 
2. tests passed 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/16170560/113883057-29e20680-9801-11eb-9d53-fb5ee68641b1.png">
3. AFAIK backed service identifies \n for "label". I'm not sure where is this code, so I grab position of CR from `layout.label`

**Comment by birsanv** [comment]
@mancubus77 tests still fail and you have one conflicting file
To check on the failed test you can:
- run the test from your workspace (npm run test) https://github.com/open-cluster-management/application-ui#npm-commands
- check the error on the PR ;click Details > Artifacts > artifacts > test > build-log.txt
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/open-cluster-management_application-ui/1068/pull-ci-open-cluster-management-application-ui-main-unit-tests/1379425536220073984/artifacts/test/build-log.txt
<img width="970" alt="Screen Shot 2021-04-07 at 10 44 37 AM" src="https://user-images.githubusercontent.com/43010150/113886433-aab3ea80-978e-11eb-8398-1908017f6352.png">

**Comment by richiepiya** [comment]
I updated the PR with the latest from main so there shouldn't be any conflicts now. 

Aside from that, I was playing with the jsfiddle link provided and I'm not sure it's working as intended:
- with a character limit of 18, for the resource type: "SecurityContextConstraints" (26 letters), I expect it to be split into "SecurityContext" (15 chars) and "Constraints" (11 chars) but it's keeping the entire string. 
- When I lower the limit to 15 (which is the character count for "SecurityContext"), it splits properly.. so even if it's just 1 character over, it takes the entire word until the next capital letter.

My example with limit 18 and "SecurityContextConstraints" label: https://jsfiddle.net/h63wypk7/

As for the issue of text sizes on zoom, it does overlap when the nodes are zoomed out. However, since this label is 21 characters long, it should be split into 2 so it should fit okay. 

<img width="459" alt="Screen Shot 2021-04-07 at 3 44 02 PM" src="https://user-images.githubusercontent.com/39634227/113924853-4dcd2a00-97b8-11eb-8874-0720be79e9b5.png">

I also tried using other labels together like "SecurityContextConstraints" and "InMemoryChannel". With the 18 character limit, the top rows would be "SecurityContext" (15 chars) and "InMemoryChannel" (15 chars) but as seen in the screenshot below, they overlap when zoomed out... so I'm not sure if going by character count is the best way.

<img width="387" alt="Screen Shot 2021-04-07 at 3 50 50 PM" src="https://user-images.githubusercontent.com/39634227/113925577-304c9000-97b9-11eb-8bd1-8b7a3e5f737d.png">

**Comment by mancubus77** [comment]
@richiepiya good point!
I slightly reworked snipped and made test https://jsfiddle.net/2ugoz8bt 
I do understand your concerns about overlap and probably it can be fixed via distance variable controlled by d3, including CR (\n), therefore this method controls CR and makes it nice despite how D3. 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/16170560/114032513-b652fe80-98bf-11eb-8221-01c22d1ae0d5.png">
I commit new version, curious to know how picture above will look like now.

**Comment by richiepiya** [comment]
Looks good from what I've tested. Thanks!

<img width="1109" alt="Screen Shot 2021-04-08 at 3 41 02 PM" src="https://user-images.githubusercontent.com/39634227/114086644-dadbb600-9880-11eb-9e25-4c45bb94c13c.png">

**Comment by richiepiya** [comment]
As of right now, we have no way of running the e2e tests on private branch PRs so I've copied your changes into a new branch on app-ui: https://github.com/open-cluster-management/application-ui/pull/1081

**Comment by richiepiya** [comment]
The changes have been merged into our app-ui main branch. Thanks @mancubus77!

**Comment by mancubus77** [comment]
Legend! 
Thank you for your support, collaboration and patience!
@richiepiya  @birsanv 👍 👍 👍
